### PR TITLE
fix(docs): broken `not valid JSON` tutorial/keymap-drawings

### LINKED ISSUE #649: doc: <TutorialFallback filename="char"/> JSON.parse: unexpected character at line 1 column 1 of the JSON data
https://github.com/ki-editor/ki-editor/blob/bff6f6fa0c3d428781ac8613db78b462a64b75d2/docs/docs/normal-mode/selection-modes/primary.md?plain=1#L194

Image

### LINKED ISSUE #670: Docs for Other Movements have a broken keyboard map
https://ki-editor.github.io/ki-editor/docs/normal-mode/other-movements

seems to have broken JSON:

Image

As an aside, I wish PageUp/PageDown keys were mapped to scrolling up and down.

### LINKED ISSUE #680: doc: Other movements keymap not show
Image

It looks like the requested file returns a 404 code.

### LINKED ISSUE #767: fix(docs/interactive-tutorial): broken with message `Unexpected token '<', "<!doctype "... is not valid JSON`
At a couple of places in the docs-site I have noticed broken tutorials:

Image

All of the places in the docs-site where this occurs:

- [x] [normal-mode/search-config#match-whole-word](https://ki-editor.github.io/ki-editor/docs/normal-mode/search-config#1-match-whole-word)
- [x] [normal-mode/other-movements#keymap](https://ki-editor.github.io/ki-editor/docs/normal-mode/other-movements#keymap)
- [x] [normal-mode/selection-modes/primary#subword](https://ki-editor.github.io/ki-editor/docs/normal-mode/selection-modes/primary#subword)
- [x] [normal-mode/selection-modes/primary#char](https://ki-editor.github.io/ki-editor/docs/normal-mode/selection-modes/primary#char)
- [ ] ...

This issue is to report and remedy this.

### PR DESCRIPTION
**Pull request by haxfn**
…'<', "<!doctype "... is not valid JSON

Fixes #767 
Fixes #680 
Fixes #670 
Fixes #649

### CODE REVIEW

File: src/recipes.rs [hunk 1]
```diff
@@ -986,6 +1005,21 @@ foo ha"
...
+                events: keys!("q w space h e l l o enter l"),
+                expectations: Box::new([CurrentSelectedTexts(&["hello"])]),
+                terminal_height: Some(7),
+                similar_vim_combos: &[],
+                only: false,
+            }]
+            .to_vec(),
+        },
         RecipeGroup {
             filename: "match-whole-subword",
```
Comment (wongjiahau) [inline src/recipes.rs:1024]: I think you can just rename `match-whole-subword` to `match-whole-word`

**Comment by wongjiahau** [comment]
Thanks!
